# Generated by Django 4.0.1 on 2022-06-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_added',
            new_name='dateadded',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='last_updated',
            new_name='lastupdated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='proj_description',
            new_name='projdescription',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='proj_link',
            new_name='projlink',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='proj_name',
            new_name='projname',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='proj_type',
            new_name='projtype',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user_id',
            new_name='userid',
        ),
    ]
