# Generated by Django 4.0.1 on 2022-06-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_date_added_project_dateadded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='dateadded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='lastupdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projdescription',
            new_name='proj_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projlink',
            new_name='proj_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projname',
            new_name='proj_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projtype',
            new_name='proj_type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='userid',
            new_name='user_id',
        ),
    ]
