# Generated by Django 4.0.1 on 2022-01-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employment',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
