# Generated by Django 4.0.1 on 2022-06-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_education_options_alter_employment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execsummary',
            options={'verbose_name_plural': 'Executive_Summary'},
        ),
    ]
